### ISSUE TITLE
下载了1.0.4 版本导入到as中编译出错

### ISSUE THREAD

**Issue by wangjianxiang** [Lowae/Design-WanAndroid#1]
![image](https://user-images.githubusercontent.com/16184489/178628941-50612fcf-8a57-40e9-91e6-d367fc6dc4b4.png)

as版本：Android Studio Chipmunk | 2021.2.1 Patch 1

gradle版本: gradle-7.4.2-bin

jdk: 1.8

**Comment by wangjianxiang** [comment]
麻烦有空的时候帮忙看下，对hit那块还没怎么研究，希望先把项目运行起来，看下功能

**Comment by Lowae** [comment]
Gradle Setting 里把JDK换成11的试试，目前项目里都是用的11，8没试过

**Comment by wangjianxiang** [comment]
jdk 11 也还是爆同样的错误， 你那边gradle用的什么版本啊

**Comment by Lowae** [comment]
版本一样的，都是gradle版本: gradle-7.4.2-bin
看下是不是网络原因，或者试下这里的方法...
https://stackoverflow.com/questions/65303346/the-hilt-android-gradle-plugin-is-applied-but-no-com-google-daggerhilt-android

**Comment by wangjianxiang** [comment]
可以了 ， 感觉应该是网络问题导致hilt的依赖未下载好，编译出错了，谢了哈

**Comment by SherlockGougou** [comment]
我这边也遇到了这个问题，应该不是网络问题诶，其他依赖都能正常拉取，只有hilt这个提示错误。

**Comment by SherlockGougou** [comment]
The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.

**Comment by wangjianxiang** [comment]
> 我这边也遇到了这个问题，应该不是网络问题诶，其他依赖都能正常拉取，只有hilt这个提示错误。

你看下 依赖是否都下载下来啊

**Comment by 603751448** [comment]
The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.
全都是这个问题欸

**Comment by easywangzhe** [comment]
The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.
同问题，改版本啥的都没用

**Comment by nanixiaoseng** [comment]
Deps.kt里面把verCode直接换成=一个数值就可以了

**Comment by wangjianxiang** [comment]
> Deps.kt里面把verCode直接换成=一个数值就可以了

是的 我也改了 现在是能正常运行起来的
