### ISSUE TITLE
编译报错：The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.

### ISSUE THREAD

**Issue by danxinzhicheng** [Lowae/Design-WanAndroid#3]
The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.

**Comment by Gennki** [comment]
+1

**Comment by Lowae** [comment]
可参考Issue:
https://github.com/Lowae/Design-WanAndroid/issues/1
